'use client'
import React from 'react'
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
// import { Metadata } from 'next'

import theme from '@/theme/theme'
import Header from '@/components/header'

// export const metadata: Metadata = {
//   title: '#SM front-end developer',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <link href='https://use.typekit.net/nvb0lhh.css' rel='stylesheet' />
      </head>
      <body style={{ height: '3000px' }}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <ChakraProvider theme={theme}>
          <Header />
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
