import React from 'react'
import { Metadata } from 'next'

import Header from '@/components/header'
import Footer from '@/components/footer'

import Providers from './providers'

export const metadata: Metadata = {
  title: '#SM',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <link href='https://use.typekit.net/nvb0lhh.css' rel='stylesheet' />
      </head>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
